#!/usr/bin/env python3
"""Generate version_rc.h for cr's lua.dll + run.exe.

Version tuple: <luajit-major>.<luajit-minor>.<yymm>.<dd>
String detail: "<tuple> (micront/<sha> luajit/<sha>)"

Date is the micront HEAD commit date (not wall clock) so a given
commit always stamps to the same version.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

HERE      = Path(__file__).resolve().parent           # src/cr/
REPO_ROOT = HERE.parents[1]                           # micront/
LUAJIT    = HERE / "luajit"


def git(cwd: Path, *args: str) -> str:
    return subprocess.check_output(
        ["git", "-C", str(cwd), *args],
        text=True, stderr=subprocess.DEVNULL,
    ).strip()


def luajit_major_minor() -> tuple[int, int]:
    text = (LUAJIT / "src" / "luajit_rolling.h").read_text()
    m = re.search(r'#define\s+LUAJIT_VERSION\s+"LuaJIT\s+(\d+)\.(\d+)', text)
    if not m:
        sys.exit("genver: can't find LUAJIT_VERSION in luajit_rolling.h")
    return int(m[1]), int(m[2])


TEMPLATE = """\
/* Auto-generated by src/cr/genver.py — do not edit. */
#ifndef CR_VERSION_RC_H
#define CR_VERSION_RC_H
#define CR_FILEVERSION     {tup}
#define CR_FILEVERSION_STR "{detail}"
#define CR_COPYRIGHT_STR   "{year}"
#endif
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    mn_sha   = git(REPO_ROOT, "rev-parse", "--short=7", "HEAD")
    lj_sha   = git(LUAJIT,    "rev-parse", "--short=7", "HEAD")
    date_iso = git(REPO_ROOT, "log", "-1", "--format=%cs", "HEAD")   # YYYY-MM-DD
    y, m, d  = (int(x) for x in date_iso.split("-"))
    yymm     = (y % 100) * 100 + m
    major, minor = luajit_major_minor()

    tup    = f"{major},{minor},{yymm},{d}"
    detail = f"{major}.{minor}.{yymm}.{d} (micront/{mn_sha} luajit/{lj_sha})"
    new    = TEMPLATE.format(tup=tup, detail=detail, year=y)

    if args.out.exists() and args.out.read_text() == new:
        return 0
    args.out.write_text(new)
    print(f"{args.out.name}: {detail}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
