#!/bin/bash
#
# gen_objects.sh - Generate obj\_objects.mac files from SOURCES
#
# BUILD.EXE normally generates these, but we can do it ourselves
# by parsing the SOURCES files to extract source file lists.
#
# Usage: gen_objects.sh <component_dir>
#   e.g.: gen_objects.sh NT/PRIVATE/NTOS/KE/UP
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
COMP_DIR="$1"

if [ -z "$COMP_DIR" ]; then
    echo "Usage: $0 <component_dir>"
    exit 1
fi

# Make path absolute if relative
if [[ "$COMP_DIR" != /* ]]; then
    COMP_DIR="$SCRIPT_DIR/$COMP_DIR"
fi

SOURCES_FILE="$COMP_DIR/SOURCES"
if [ ! -f "$SOURCES_FILE" ]; then
    echo "ERROR: SOURCES file not found: $SOURCES_FILE"
    exit 1
fi

# Check for arch-specific sources:
# 1. In a separate I386/SOURCES file (e.g., KE/I386/SOURCES)
# 2. As i386_SOURCES= in the main SOURCES file itself (e.g., VDM/UP/SOURCES)
I386_SOURCES=""
for candidate in "$COMP_DIR/I386/SOURCES" "$COMP_DIR/../I386/SOURCES" "$COMP_DIR/i386/SOURCES" "$COMP_DIR/../i386/SOURCES"; do
    if [ -f "$candidate" ]; then
        I386_SOURCES="$candidate"
        break
    fi
done
# If no separate file, check if i386_SOURCES is defined in the main SOURCES
if [ -z "$I386_SOURCES" ]; then
    if grep -q "i386_SOURCES" "$SOURCES_FILE" 2>/dev/null; then
        I386_SOURCES="$SOURCES_FILE"
    fi
fi

mkdir -p "$COMP_DIR/obj/i386"

# Parse source files from SOURCES file
# We need to extract the SOURCES= macro value, handling line continuations (\)
extract_sources() {
    local file="$1"
    local varname="$2"

    # Extract the variable assignment, joining continuation lines
    awk -v var="$varname" '
    BEGIN { found=0; }
    $0 ~ "^"var"=" || $0 ~ "^"var" =" {
        found=1;
        sub("^"var"[[:space:]]*=[[:space:]]*", "");
    }
    found {
        # Remove trailing backslash and whitespace
        cont = ($0 ~ /\\[[:space:]]*$/);
        sub(/\\[[:space:]]*$/, "");
        # Print the filenames
        gsub(/^[[:space:]]+/, "");
        gsub(/[[:space:]]+$/, "");
        if ($0 != "") print $0;
        if (!cont) found=0;
    }
    ' "$file" | tr -s ' \t' '\n' | sed '/^$/d'
}

# Convert a source filename to its object filename
# ..\foo.c -> obj\i386\foo.obj
# ..\i386\bar.asm -> obj\i386\bar.obj
# ..\i386\baz.c -> obj\i386\baz.obj
src_to_obj() {
    local src="$1"
    # Normalize backslashes to forward slashes for basename
    src="${src//\\//}"
    local base
    base=$(basename "$src")
    local ext="${base##*.}"
    # Skip .rc files — resource files are handled separately by MAKEFILE.DEF
    if [ "$ext" = "rc" ] || [ "$ext" = "RC" ]; then
        return 1
    fi
    base="${base%.*}"
    echo "obj\\i386\\${base}.obj"
}

# Collect all source files
ALL_SOURCES=()

# Main SOURCES
while IFS= read -r src; do
    [ -n "$src" ] && ALL_SOURCES+=("$src")
done < <(extract_sources "$SOURCES_FILE" "SOURCES")

# I386-specific sources
if [ -n "$I386_SOURCES" ]; then
    while IFS= read -r src; do
        [ -n "$src" ] && ALL_SOURCES+=("$src")
    done < <(extract_sources "$I386_SOURCES" "i386_SOURCES")
fi

# Also check for NTTARGETFILES in SOURCES
NTTARGETFILES=""
while IFS= read -r src; do
    [ -n "$src" ] && NTTARGETFILES="$src"
done < <(extract_sources "$SOURCES_FILE" "NTTARGETFILES")

# Build the _objects.mac file
OBJMAC="$COMP_DIR/obj/_objects.mac"
{
    echo "#"
    echo "# _objects.mac - generated by gen_objects.sh"
    echo "#"
    echo ""

    # Build 386_OBJECTS line
    printf "386_OBJECTS="
    first=true
    for src in "${ALL_SOURCES[@]}"; do
        obj=$(src_to_obj "$src") || continue
        if $first; then
            printf "%s" "$obj"
            first=false
        else
            printf " \\\\\n    %s" "$obj"
        fi
    done
    printf "\n\n"

} > "$OBJMAC"

echo "Generated $OBJMAC with ${#ALL_SOURCES[@]} source files"
