#!/usr/bin/env python3
"""
pe2gdb.py - Extract PE export symbols for GDB debugging

Generates a GDB command file that defines convenience variables for all
exported functions. Load in GDB with: source <output_file>

Usage:
    pe2gdb.py <pe_file> [<output_file>]
    pe2gdb.py NT/.../ntoskrnl.exe boot/ntoskrnl.gdb
    pe2gdb.py NT/.../hal.dll boot/hal.gdb

In GDB:
    source boot/ntoskrnl.gdb
    source boot/hal.gdb
    hbreak *$KeBugCheckEx
    hbreak *$HalInitSystem
"""

import struct
import sys
import os


def parse_pe_exports(filepath):
    with open(filepath, "rb") as f:
        data = f.read()

    if data[:2] != b'MZ':
        raise ValueError(f"Not a PE file: {filepath}")

    dos_e_lfanew = struct.unpack_from("<I", data, 0x3C)[0]
    nt_sig = struct.unpack_from("<I", data, dos_e_lfanew)[0]
    if nt_sig != 0x4550:
        raise ValueError(f"Bad PE signature: {nt_sig:#x}")

    opt_off = dos_e_lfanew + 24
    image_base = struct.unpack_from("<I", data, opt_off + 28)[0]
    num_rva_sizes = struct.unpack_from("<I", data, opt_off + 92)[0]
    if num_rva_sizes < 1:
        return image_base, []

    export_rva = struct.unpack_from("<I", data, opt_off + 96)[0]
    if export_rva == 0:
        return image_base, []

    num_sections = struct.unpack_from("<H", data, dos_e_lfanew + 6)[0]
    opt_size = struct.unpack_from("<H", data, dos_e_lfanew + 20)[0]
    sec_start = dos_e_lfanew + 24 + opt_size

    def rva_to_offset(rva):
        for i in range(num_sections):
            off = sec_start + i * 40
            va = struct.unpack_from("<I", data, off + 12)[0]
            raw = struct.unpack_from("<I", data, off + 20)[0]
            vs = struct.unpack_from("<I", data, off + 8)[0]
            if va <= rva < va + vs:
                return rva - va + raw
        return None

    exp_off = rva_to_offset(export_rva)
    if exp_off is None:
        return image_base, []

    num_names = struct.unpack_from("<I", data, exp_off + 24)[0]
    func_rva_table = struct.unpack_from("<I", data, exp_off + 28)[0]
    name_rva_table = struct.unpack_from("<I", data, exp_off + 32)[0]
    ord_table = struct.unpack_from("<I", data, exp_off + 36)[0]

    exports = []
    for i in range(num_names):
        n_rva = struct.unpack_from("<I", data, rva_to_offset(name_rva_table) + i * 4)[0]
        n_off = rva_to_offset(n_rva)
        name = data[n_off:data.index(b'\0', n_off)].decode('ascii', errors='replace')
        ordinal = struct.unpack_from("<H", data, rva_to_offset(ord_table) + i * 2)[0]
        func_rva = struct.unpack_from("<I", data, rva_to_offset(func_rva_table) + ordinal * 4)[0]
        exports.append((func_rva + image_base, name))

    exports.sort()
    return image_base, exports


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    pe_path = sys.argv[1]
    if len(sys.argv) > 2:
        out_path = sys.argv[2]
    else:
        base = os.path.splitext(os.path.basename(pe_path))[0]
        out_path = base + ".gdb"

    image_base, exports = parse_pe_exports(pe_path)

    with open(out_path, "w") as f:
        f.write(f"# GDB symbols for {os.path.basename(pe_path)}\n")
        f.write(f"# Generated by pe2gdb.py — {len(exports)} exported symbols\n")
        f.write(f"# ImageBase: {image_base:#010x}\n")
        f.write(f"# Usage: source {out_path}\n")
        f.write(f"#        hbreak *$KeBugCheckEx\n\n")

        for addr, name in exports:
            f.write(f"set ${name} = {addr:#010x}\n")

    print(f"{os.path.basename(pe_path)}: {len(exports)} symbols -> {out_path}")


if __name__ == "__main__":
    main()
